### PR TITLE
bugfix: sum up the client total and online values

### PR DESCRIPTION
**Pull request by simonkurka**

### CODE REVIEW

**Comment by tantive** [comment]
Heh, ok, implemented it the same way as well:


diff --git a/modules/provider/prometheus-metrics.js b/modules/provider/prometheus-metrics.js
index 3d6aebd..608f5c1 100644
--- a/modules/provider/prometheus-metrics.js
+++ b/modules/provider/prometheus-metrics.js
@@ -88,16 +88,21 @@ module.exports = function(receiver, config) {
       if (_.has(n, 'nodeinfo.network.mesh')) {
         for (let bat in n.nodeinfo.network.mesh) {
           for (let type in n.nodeinfo.network.mesh[bat].interfaces) {
             n.nodeinfo.network.mesh[bat].interfaces[type].forEach((d) => {
               typeTable[d] = type
             })
           }
         }
       }
       counter.meshnodes.total++
+      counter.clients.total += get(n, 'statistics.clients.total')
 
-      if (isOnline(n))
+      if (isOnline(n)) {
         counter.meshnodes.online++
+        counter.clients.online += get(n, 'statistics.clients.total')
+      }
 
       var labels = {}
       labels['nodeid'] = k
@@ -141,8 +146,7 @@ module.exports = function(receiver, config) {
         labels['type'] = 'tx'
         save(n, stream, labels, 'statistics.traffic.mgmt_tx.bytes', 'statistics_traffic')
       }
-
-      counter.clients += get(n, 'statistics.clients.total')
+  
       counter.traffic.forward += get(n, 'statistics.traffic.forward.bytes')
       counter.traffic.rx += get(n, 'statistics.traffic.rx.bytes')
       counter.traffic.tx += get(n, 'statistics.traffic.tx.bytes')

**Comment by simonkurka** [comment]
you should put
`counter.clients.online += get(n, 'statistics.clients.total')` into the `if (isOnline(n, 'statistics')) {` block. It ensures, that there are statistics, but it's nit a big deal... works both.

**Comment by simonkurka** [comment]
@plumpudding @tantive 
I just noticed that it IS a big deal if we use
`if (isOnline(n)) {
  counter.clients += get(n, 'statistics.clients.total')
}`

or

`if (isOnline(n, 'statistics')) {
  counter.clients += get(n, 'statistics.clients.total')
}`

I get values which differ by round about 700 (~150 to ~850), although I set metricsOfflineTime and offlineTime to the same value.

Can you explain why? What is the correct here?

Thank you in advance!

**Comment by simonkurka** [comment]
Maybe we should continue in #65

**Pull request merged**
