### PR TITLE
hopglass provider: added nexthop and airtime

### PR DESCRIPTION
**Pull request by eberhab**
as the statistics values are extracted individually this change is required for https://github.com/plumpudding/hopglass/pull/38

### CODE REVIEW

**Comment by plumpudding** [comment]
Are there any other locations for this info? I would like to use the server to make it compatible with different implementations. I.e. if there was an implementation with "nodeinfo.network.wireless" the server should copy that to "node.statistics.wireless".

**Comment by eberhab** [comment]
I dont currently know of any other locations being used. This is why I suggested to have the hopglass PR open for a week in order to collect input. Eventually we'll PR these quantities to gluon so everyone will use the same locations. Until then I suggest people temporarily PR their locations to hopglass-server in the way you proposed or they open an issues about it.

**Comment by rotanid** [comment]
what if a node has more than one 2,4 or 5ghz wifi device?
i think it would be better to not hardcode that and just iterate over all available wifis

**Comment by eberhab** [comment]
This is primarily a gluon issue but I agree that it would be better. This has been discussed before but then people seemed to prefer it the way it is now:
https://github.com/freifunk-ffm/map-server-config/issues/4#issuecomment-222608118

All respondd implementations that i know of so far report chan<2|5> etc, assuming that the first device would always be 24 and the second device would be 5. But I havent followed the gluon development on the transmission of these quantities for a while. As soon as there is a working solution in gluon master someone should probably just adapt it here. So I think this discussion makes more sense on the gluon side. Not sure what the current status is though. This is all I know:
https://github.com/freifunk-gluon/packages/issues/138

**Comment by rotanid** [comment]
well, unfortunately many people do gluon forks and gluon packages the quick&dirty way and without upstreaming them, that makes me sad and leads to more and more fragmentation of the "gluon-ecosystem" and therefore more work for everyone.
like in the case of this airtime-change, it is simply wrong that the first device is always 24, my dual-band devices are exactly the opposite for example - and we also use devices with more than just two radio-devices (like adding a wifi-usb-stick for example)
i hope that some day people will stop the quick&dirty stuff **and** do more upstreaming...

**Pull request merged**
