### PR TITLE
Resolve node id from gateway mac address.

### PR DESCRIPTION
**Pull request by mar-v-in**
As discussed in plumpudding/hopglass#42.

### CODE REVIEW

**Comment by plumpudding** [comment]
Can you please remove that uplink flag thing? It doesn't solve the problem, because not all supernodes are gateways.

**Comment by mar-v-in** [comment]
I know this only works for some networks, but some is better than none, and we do not have any better data for l2tp yet.

I think it is a good idea to add something similar to add support for `statistics.mesh_vpn` peer group data to the gluon-mesh-vpn-tunneldigger package, together with respondd support, but until now, we should do the best we can with current data.

Nonetheless I can split these things into separate PRs.

**Comment by plumpudding** [comment]
Please split the PRs. Further discussion on uplink detection will be in the second PR.

**Comment by mar-v-in** [comment]
Done.

**Pull request merged**
