### PR TITLE
add support for meshviewers nodes.json v1

### PR DESCRIPTION
**Pull request by rotanid**
this change adds support for the nodes.json v1 dataformat of meshviewer which is used by latest "stable" "official" release v4 of ffnord/meshviewer

### CODE REVIEW

**Comment by plumpudding** [comment]
Please put that in a separate provider, so that we can support both. I have to take a close look. Last time I accepted a PR without inspecting every single character, it totally blew up on me.

**Comment by rotanid** [comment]
thanks for your feedback.
this already supports both, you can test it there: https://map.tecff.de/hopglass-server/
i could put it in a separate provider, but that would lead to much code being duplicated for no reason - do you want that?

**Comment by plumpudding** [comment]
oh, I see.. Then it's ok.

**Comment by rotanid** [comment]
@plumpudding i added a commit to also put the new endpoints in the README.
do you have any further change requests before it can be merged?

**Pull request merged**
